version: '3.7'
services:
  mysqldb:
    image: mysql:latest
    hostname: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - 3306:3306


  adminer_container:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: mysqldb
    ports:
      - 8080:8080
